src/main/python/gui/hand_configuration.py
src/main/python/gui/handshape_selector.py
src/main/python/gui/main_window.py
src/main/python/gui/module_selector.py
src/main/python/gui/movement_selector.py
src/main/python/gui/panel.py
src/main/python/gui/predefined_handshape_dialog.py
src/main/python/gui/xslot_graphics.py
src/main/python/gui/xslots_selector.py
src/main/python/lexicon/lexicon_classes.py

rewrite backend and gui code to avoid redundancy when dealing with different parameter modules

Modulemodularityrefactor

---

src/main/python/gui/main_window.py
src/main/python/gui/signlevelinfo_selector.py
src/main/python/lexicon/lexicon_classes.py

also reorganized layout of the sign-level info dialog box

added "fingerspelled" to sign-level info as per issue #93

---

src/main/python/gui/location_view.py
src/main/python/gui/movement_view.py
src/main/python/lexicon/lexicon_classes.py

- add sub-areas for "whole hand" and "hand minus fingers"
- restructure the way that locationtablemodel details are fetched from serialized copies
- create a common parent class for serializable location and movement modules

address issue #84

---

src/main/python/gui/signtype_selector.py
src/main/python/lexicon/lexicon_classes.py

- including backward compatibility to load signs that were created prior to this added info being available
- cleaned up commented/unused code in signtype_selector.py

implement signtype notes #96

---

src/main/python/gui/modulespecification_widgets.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py

implemented backward compatibility via checking for 'iconic' attributes in AddedInfo class itself

add 'iconic' to right-click and 'module notes' menus

---

src/main/python/gui/bodypartspecification_dialog.py
src/main/python/gui/handconfigspecification_view.py
src/main/python/gui/helper_widget.py
src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/movementspecification_view.py
src/main/python/gui/panel.py
src/main/python/gui/relationspecification_view.py
src/main/python/gui/xslot_graphics.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py
src/main/python/models/relation_models.py
src/main/python/serialization_classes.py

100 relation module 2

---

src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/relationspecification_view.py
src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py

un/bold styling on "specify body parts" buttons in relation module

---

src/main/python/gui/relationspecification_view.py

Relation module: ensure that if x-slots are off, availability of 'contact manner' doesn't depend on timing interval selection

---

src/main/python/gui/locationspecification_view.py

Added to the clear() method which handles resetting entered data. It now includes code to reset the sorting options as well as the panels with some comments for clarity.

147 restore defaults location

---

src/main/python/gui/main_window.py
src/main/python/gui/panel.py
src/main/python/gui/preference_dialog.py
src/main/python/gui/signtypespecification_view.py

Create global setting for default signtype.

21 lower sign type options greyed out for new signs

---

src/main/python/gui/panel.py
src/main/python/gui/signlevelinfospecification_view.py

Issue #236 
Casting numdigits value to an integer to fix issue where this value is some how turned into a string.
Action item: follow up on other settings that may have misspecified types, see if this is related to the OS that SLPAA is being run on

236 bugfix cast entryid int

---

src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/orientationspecification_view.py
src/main/python/gui/panel.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py

Issue #75 
Orientation module unlocked, still confirming that module options can be appropriately loaded and saved.

Unlocking orientation module

---

src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/models/movement_models.py

also side quest: adding equality methods for some module-subsidiary classes that didn't already have them

simplify attribute equality checking when updating module

---

src/main/python/lexicon/module_classes.py

make text less ambiguous for non-displayed entry id

---

src/main/python/constant.py
src/main/python/gui/countxslots_dialog.py
src/main/python/gui/main_window.py
src/main/python/gui/mergecorpora_dialog.py
src/main/python/gui/modulespecification_widgets.py

A not-super-official merge function is added to the Analysis Functions (beta) menu, to make it easier to prep for LREC 2024. This merge ensures that EntryIDs are not duplicated, and will report any duplicate glosses and/or lemmas (user needs to copy the list to double-check before closing the merge dialog).
Further polishing/features/options to come in #275

299 side script minimally viable merge before lrec 2024

---

src/main/python/gui/corpus_view.py
src/main/python/gui/countxslots_dialog.py
src/main/python/gui/decorator.py
src/main/python/gui/main_window.py
src/main/python/gui/mergecorpora_dialog.py
src/main/python/gui/panel.py
src/main/python/gui/preference_dialog.py
src/main/python/gui/signlevelinfospecification_view.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/models/corpus_models.py

fixes #105 , fixes #281 , fixes #300 , fixes #301 , fixes #303 
updates #238 
requesting review from @gracemyz to make sure revised backward-compatibility movement/location conversion code still works as intended

105 additional glosses for each sign

---

src/main/python/gui/decorator.py
src/main/python/gui/signlevelinfospecification_view.py

one more tweak as per issue #105 and to add on to PR #304

strip whitespace from start/end of glosses, lemmas, and id-glosses

---

src/main/python/gui/panel.py

makes for better alignment with the new corpus _table_ (instead of _list_)

rearrange sign level menu layout so that it is more horizontal and less vertical

---

src/main/python/gui/main_window.py

set new default layout to accommodate new size and shape of sign level menu and corpus list subwindows

---

src/main/python/gui/handconfigspecification_view.py

... though this doesn't seem to be as drastic of an issue as it used to?

refined hand illustration sizing a bit

---

src/main/python/gui/corpus_view.py

differentiate total signs in corpus from total lines in corpus view (depends on glosses)

---

src/main/python/gui/helper_widget.py
src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/movementspecification_view.py
src/main/python/gui/panel.py

User experience is still the same; back end is just tidier / more modular.

342 tidy up unused/nonfunctional code in movement and location comboboxes

---

src/main/python/gui/corpus_view.py

change filter text label to "x of y glosses shown" instead of "lines"

---

src/main/python/gui/handconfigspecification_view.py
src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/movementspecification_view.py
src/main/python/gui/nonmanualspecification_view.py
src/main/python/gui/orientationspecification_view.py
src/main/python/gui/relationspecification_view.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/serialization_classes.py

Addresses: #169 
- Moved phonloc selection widget from Location view to ModuleDialog 
- Moved phonlocdata from LocationModule into ParameterModule
- Modified necessary information in serialization_class and lexicon_class files
Demo:

169: Add phonetic phonological options all

---

src/main/python/gui/main_window.py

Stanley already removed ellipsis for Load Sample Corpus.

remove ellipsis on preferences menu item

---

src/main/python/constant.py
src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py

224 include hand leg arm part selected in the relation module tooltip in the summary window

---

src/main/python/search/helper_functions.py
src/main/python/search/search_models.py

Also fixes a bug in Location search where both Body and Body-anchored loctypes were being returned regardless of the target location type.

420 make location details tables searchable

---

src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py
src/main/python/models/movement_models.py
src/main/python/search/helper_functions.py
src/main/python/search/search_builder.py
src/main/python/search/search_classes.py
src/main/python/search/search_models.py

This update also refactors some of the search logic so that the Relation module and the Location module use the same functions for location and details tables searches.

426 make details tables searchable in relation modules and associated relation modules

---

src/main/python/gui/decorator.py
src/main/python/gui/main_window.py
src/main/python/search/results.py
src/main/python/search/search_builder.py

* Add an "export" button to individual and summary results tabs. 
* Keyboard shortcut is Alt-E.
* Allowed export formats are XML, JSON, txt, and TSV. Default is XML
* Remember recent folders for search results and search targets.

433 add save feature for search results
