src/main/python/lexicon/module_classes2.py

module instances that take up the whole sign have an arbitrary startpoint/endpoint convention that was being missed when checking for interval overlaps

fix issue #80

---

src/main/python/gui/signtypespecification_view.py

User is not allowed to save and shown a warning if "H1 and H2 are bilaterally symmetric" is selected AND
- H1/H2 have different hand configurations OR
- Only 1 hand moves OR
- Both hands move but they move differently

79 check dependencies when saving signtype module

---

src/main/python/models/movement_models.py

- I haven't assigned unique values for the unused `node_id` key of these new options as it would mean updating the values for a hundred or so more options below in the movement tree. Since they're just placeholders for now, I hope that's okay. (You've probably thought more about this, but if we want ordered unique ids for the tree nodes, maybe they could be assigned during the tree traversal in `populate()` instead of hardcoding the numbers?) 
- Added the new options to section 1.2 of the internal documentation.

Add 'fully rotating' option to joint-specific options of movement tree

---

src/main/python/models/location_models.py

Instead of adding `dorsum, blade, tip` to the `subareas_nonhand_default` list, I created a new default list for the tongue alone. I think this is better than updating the exceptions lists for all other nonhand locations. 
The change should be backward compatible (tongue location options added before the change are maintained after the change)

Add new subareas_tongue_default list with dorsum, blade, tip included

---

src/main/python/models/movement_models.py

Directionality and its suboptions are disabled/enabled when Wiggling/Fluttering is selected/deselected, as requested. However, for some reason the suboptions don't get greyed out even though they are disabled:
I tried `QStandardItem.setForeground()` to manually set the text color to gray, but this didn't work either. It might be a problem with the style for radio buttons, since I was able to use `setForeground()` successfully with all the checkboxes in the movement tree, but none of the radio buttons. 
Should I continue trying to find a way to grey out the suboptions, or is it okay as is?

83 disable directionality when fluttering is selected

---

src/main/python/gui/main_window.py
src/main/python/lexicon/module_classes.py

Added code for `compoundsign` everywhere I could see that it was missing, except for the `on_action_export_handshape_transcription` method in in `main_window.py`. I saw that the method might be overhauled later so I just left a comment, but let me know if I should add the `compoundsign` code.

150 sign level information compound sign checkbox does not save properly

---

src/main/python/models/movement_models.py

- Added specific directional choices for each circumduction option (**backward compatible**)
- Separated non-base interphalangeal finger joints into distal and proximal finger joints (**not backward compatible**)
- Separated options for four fingers separately instead of 'fingers' as a single group (**not backward compatible**)

Update joint activity options

---

src/main/python/models/location_models.py

Created a new list of surfaces for the heel of hand, as in #139, and changed the subareas to the `subareas_hand_default` list.
If we anticipate adding a lot of new surfaces or subareas to the existing default lists, would it be worth updating the location tree to allow these kinds of exceptions? At the moment the exceptions lists only allow us to _exclude_ from the default lists.

Update surfaces and subareas for heel of hand

---

src/main/python/gui/signlevelinfospecification_view.py

Created a `restore_defaults` method for the sign level info panel. To avoid code duplication, `clear()` calls `restore_defaults`. The difference is that `restore_defaults` does not reset the Modified and Created dates.

Update 'Restore Defaults' behaviour for Sign Level Info

---

src/main/python/models/location_models.py

- If a location module was saved with `Other hand` selected, leave it alone
- If a location module was saved with `Other hand>Whole hand` selected, rename it as `Other hand` and carry over its surfaces/subareas
- If a location module was saved with both `Other hand` and `Other hand>Whole hand` selected:
- Replace the former with the latter and carry over the surfaces/subareas
The backward compatibility is handled differently for this change, since it's a replacement with an existing option instead of with an entirely new option.

Collapse 'other hand>whole hand' option into 'other hand' option

---

src/main/python/models/movement_models.py

Uncheck only when disabling. The only potential pitfall of this is that when we re-enable, if there is an "other" specification then that item will get auto-checked (even if it wasn't before).

179 bug missing joint specific movements after 175178

---

src/main/python/gui/relationspecification_view.py

enable/disable 'x and y crossed' and 'x and y linked' in Relation module, depending on linked Movement module

---

src/main/python/models/movement_models.py

Modified the rubbing options for the old movement tree structure so that they're available for coders.
For the movement tree restructure, I'll find a way to make "Articulators" and "Location" show only text, as discussed in the meeting 2023-09-11.

Modify rubbing options

---

src/main/python/gui/movementspecification_view.py

The added line changes the index of sort_by combobox to the first item (i.e., order in tree (default)), as the tree model refreshes.

'restore defaults' in movement module

---

src/main/python/gui/corpus_view.py

Previously, double-clicking an item of the Corpus list appeared as if the user could change sign info. This could be misleading because it does nothing actually. 
This commit uses QAbstractItemView.NoEditTriggers to ignore a double click (and on Mac, hitting Return).

Entering into edit state is disabled on Corpus panel

---

src/main/python/models/movement_models.py

Issue #221 
Added the horizontal lines in the same way as the axis panels by wrapping the options in subgroups. The fields higher up the tree auto-select the same way in both the main branch and the version with the subgroups. A screenshot of the behaviour is left below:

Add horizontal lines to movement menu planes tab

---

src/main/python/gui/main_window.py

SLPAA internally throws an error if the user tries to load a corpus and then cancels out of the dialog (issue #229). This simple PR adds a conditional that catches this behaviour and stops the load function.
It seems simple, but please double-check to ensure I covered all use case scenarios.

Don't panic if the user cancels out of the load dialog!!

---

src/main/python/gui/initialization_dialog.py
src/main/python/gui/main_window.py

Issue #202 
Renamed the cancel button in the initialization menu to "Close"
Pressing the "Close" button or "X" now exits the program entirely.

202 stop slpaa open

---

src/main/python/models/location_models.py

Do backwards compatibility for children of "Other hand", such as "Other hand>Finger 1".
Also, deep copy the body part location trees in the Relation module, just in case we need to modify the Relation body part locations without changing the Location module.

239 bug underspecified locations in frozen pre restructure branch

---

src/main/python/gui/corpus_view.py
src/main/python/gui/signlevelinfospecification_view.py
src/main/python/models/corpus_models.py

There was an order-of-operations error in how the lastmodified date was being updated when a sign was updated. Also, the default implementation of `QSortFilterProxyModel.sort()` isn't able to compare `datetime.datetime` objects, so I deal with those explicitly and then pass the rest off.

add lemma to corpus sort options; fix bug with date-based sorting

---

src/main/python/gui/corpus_view.py
src/main/python/gui/main_window.py
src/main/python/gui/panel.py
src/main/python/gui/signlevelinfospecification_view.py
src/main/python/lexicon/lexicon_classes.py

Issue #78 - Deleting signs now highlights correctly according to expected behaviour
Case 1: There is more than 1 sign in the list, sign to be deleted is not the first in the corpus
Before deletion:
After deletion: (preceding sign is now highlighted)
Case 2: There is more than 1 sign in the list, sign to be deleted is the first in the corpus
Before deletion:
After deletion: (following sign is now highlighted)
Case 3: There is only 1 sign left in the corpus that is to be deleted.
Before deletion:
After deletion: (no signs are left in the corpus)

Deleting signs 

---

src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_widgets.py

when user opens an existing location module, highlight/select the first location option in the selected list (if any) and display its surfaces/subareas

to address issue #259

---

src/main/python/gui/panel.py

Relevant for when x-slots are turned off: ensure that the y-coordinate gets increased each time a new module's rectangle is added to the visual summary, so that they don't get stacked on top of one another.
It was just a question of moving the increment from outside a per-module loop, to inside the loop.

fix issue #261

---

src/main/python/gui/location_definer.py
src/main/python/gui/main_window.py

Although clicking on the tool bar does not crash the program on my end, I did find that two options triggered errors independently: 1. Settings > Preferences... and 2. Location > Define locations... This PR addresses both.
@brdiep113 Brian could you kindly check if the issues have been resolved and if the program no longer crashes?
This is from a known issue where the two settings parameters `entryid_digits` and `sig_figs` are incorrectly typed as str instead of int on Ubuntu.
So the solution was simple: explicitly type `sig_figs` and `entryid_digits` as int from the very beginning.
The location definer dialog has tabs that can be closed by clicking Ⓧ, which appear on the left or right side of the tab. The right-most tab is 'Add new tab' and we don't want the Ⓧ button for this tab. So we …

250 bug slpaa and ubuntu device crashes on toolbar selection

---

src/main/python/gui/corpus_view.py
src/main/python/gui/main_window.py
src/main/python/gui/panel.py

Ensure that if the user cancels out of creating a new sign, the software returns to focus on the previously-selected sign (including none if that's the case).

fix issue #263

---

src/main/python/lexicon/lexicon_classes.py

If the contact section is totally blank, OR the "no contact" radio button is selected, then don't warn about missing bodyparts.

Don't warn about missing bodyparts in relmod if no contact

---

src/main/python/gui/main_window.py
src/main/python/gui/panel.py
src/main/python/gui/preference_dialog.py
src/main/python/gui/signlevelinfospecification_view.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py

EntryID is now a class instead of just a counter. An EntryID is displayed pulling data on-the-fly from application QSettings and from its parent Sign, to combine various attributes (date, counter, etc) in a user-specific order, with a user-selected delimiter.
We can also set the minimum counter value for a corpus-- either by the user when first creating a blank corpus, or programmatically for instance if merging corpora.

283 add entryid flexibility/functionality

---

src/main/python/gui/decorator.py
src/main/python/gui/main_window.py
src/main/python/gui/preference_dialog.py
src/main/python/lexicon/module_classes.py

- ensure EntryID settings persist correctly
- ensure settings for which subwindows are visible are saved correctly
- add a note for when Entry ID is blank (user has de-selected all potential components)

283 add entryid flexibilityfunctionality

---

src/main/python/gui/main_window.py
src/main/python/gui/preference_dialog.py

This doesn't seem to affect *all* of the fonts in the application (eg visual summary window), but it does take care of enough of them that the tiny font problem Maggie mentioned in issue #289 should be reasonably well addressed.
The best/most natural size I could determine via various resolution / text size settings on my computer was 8, so that's what I've set to be the default. Font size can be changed via Preferences menu > Display tab.

create a settings option for font size

---

src/main/python/gui/modulespecification_dialog.py

Previously, the articulator selection panel and the x-slot linking panel were created no matter what, and only added to the module specification layout if relevant. This allowed for later references to these panels without having to check for existence first. However, this approach seemed to be leaving 'ghost' traces of those panels even though they were never added to the layout. 
The new approach is to _only_ create the above panels if they are relevant. This means that further references to the panels have to be existence-checked first, to make sure we don't get any does-not-exist or NoneType errors.

188 remove ghost versions of unnecessary articulator and/or timing selection panels from top of module dialogs

---

src/main/python/models/movement_models.py

Backward compatibility for one version of the "trilled" node was handled separately since it had a specific hierarchical structure that had to be modified. For that version, the function was incorrectly expecting the `serializedmvmttree.addedinfos` dict to be containing checkboxes.

Fix backward compatibility for Trilled

---

src/main/python/gui/bodypartspecification_dialog.py
src/main/python/gui/locationspecification_view.py
src/main/python/gui/movementspecification_view.py
src/main/python/gui/panel.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py
src/main/python/models/movement_models.py

also had to change the name of the delimiter used for separating nodes in movement tree paths, for the sake of differentiating from this one

add a single point of reference for delimiter to use between glosses

---

src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/relationspecification_view.py

- contact options
- direction options
- body part selections/buttons

ensure that all Relation options are cleared/restored when choosing "save and add another" or "restore defaults"

---

src/main/python/gui/handconfigspecification_view.py

This PR modifies the way the hand configuration specification dialog is shown. 
Previously, the window was so wide that it went beyond the screen horizontally on MacOS. This PR presents widgets on many levels, making use of more vertical space. It also enlarges the predefined handshape image.
| Main  | This PR |
| ------------- | ------------- |
| <img width="500" alt="Screenshot 2024-07-24 at 7 25 49 PM" src="https://github.com/user-attachments/assets/cacc723b-b2f1-4c81-a772-31e17c59dd43">  | <img width="500" alt="Screenshot 2024-07-24 at 7 27 18 PM" src="https://github.com/user-attachments/assets/1728f3fe-157d-4e61-83ff-9ef3e3a339fa"> |
@kchall and @kvesik , can you make sure the dialog shows up as intended, especially on MacOS?

338 make hand configuration dialog less horizontal

---

src/main/python/constant.py
src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/panel.py
src/main/python/gui/signtypespecification_view.py

- Added warning dialog when we encounter scenario described in title
- deleted `includephrase` reference -- doesn't seem like it is being used?
https://github.com/user-attachments/assets/89081e14-12a1-4f3e-abf3-ff0c1ad314ab
https://github.com/user-attachments/assets/ece2d6f7-d871-4771-9c82-17059d15d96c
Note: If you toggle between the options it will reset
https://github.com/user-attachments/assets/1714b2f0-f5f1-481e-bb19-6d56eaa83c65

331: Add warning before saving "both hands" for 1 handed signs

---

src/main/python/gui/modulespecification_dialog.py
src/main/python/lexicon/module_classes.py

ensure that if there is existing x-slot information (even if x-slots are currently turned off), that the existing info is preserved in case the user wants to return to x-slots mode

fix issue #372

---

src/main/python/constant.py
src/main/python/gui/bodypartspecification_dialog.py
src/main/python/gui/corpus_view.py
src/main/python/gui/decorator.py
src/main/python/gui/link_help.py
src/main/python/gui/main_window.py
src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/movementspecification_view.py
src/main/python/gui/panel.py
src/main/python/gui/preference_dialog.py
src/main/python/gui/relationspecification_view.py
src/main/python/gui/signtypespecification_view.py
src/main/python/gui/xslot_graphics.py
src/main/python/lexicon/lexicon_classes.py
src/main/python/lexicon/module_classes.py
src/main/python/lexicon/module_utils.py
src/main/python/models/location_models.py
src/main/python/models/movement_models.py
src/main/python/models/relation_models.py
src/main/python/serialization_classes.py

fixes #191  ... other than the "copy timing" part
- fixed an issue where copying/pasting a sign with linked modules didn't keep the linking between the modules
- fixed an issue where copying/pasting a sign with several of the same type of module didn't paste all instances
- anytime user copies/pastes module(s) without their associated modules, the user is invited to copy the associated one(s) too
- if user copies/pastes modules into a sign whose timing structure differs from the original, the user is warned to double-check timing for pasted module(s)
- if user pastes signtype in another sign with existing signtype, they are asked to confirm before overwriting
- user cannot paste modules into a sign whose x-slot info isn't set up yet (assuming x-slots are "on")
- user can right-click on …

191 provide copy module and copy sign options

---

src/main/python/gui/xslot_graphics.py

(as opposed to clipboard modules)

ensure "delete module(s)" menu item checks for selected modules to determine whether enabled

---

src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/movementspecification_view.py
src/main/python/models/location_models.py
src/main/python/models/movement_models.py
src/main/python/models/shared_models.py

In the search combobox that appears in both Movement and Location module dialogs, it is now the case that:
1. choosing an item with the mouse OR by typing and pressing enter will add it to the selected list, without having to use the right arrow key
2. whether you used the mouse or the keyboard, once the item has been selected the combobox text should be cleared so that the next item can immediately be searched for

344 implement more efficient/intuitive shortcut for movement or location selection in movement or location dialog

---

src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_dialog.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/lexicon/module_classes.py
src/main/python/models/location_models.py

* Implemented Location tooltips according to the [Abbreviations ](https://docs.google.com/spreadsheets/d/1qdf72ivD_tLFBvVQgSkzesyzVF_HWb1llmc2fmaqPI8/edit?gid=1251951879#gid=1251951879)sheet
* Fixed bug in ModuleSelectorDialog where the Restore Defaults button was not clearing phonological / phonetic checkboxes
* Fixed bug in Location Module where the `This location is neutral` cb checkstate was not being saved properly when switching between location types
* Tweaks to Relation tooltips:
* Added a space in between square brackets to match the specification in the [Abbreviations ](https://docs.google.com/spreadsheets/d/1qdf72ivD_tLFBvVQgSkzesyzVF_HWb1llmc2fmaqPI8/edit?gid=1251951879#gid=1251951879)sheet:  `For surface/sub-area/joint/axis/distance info, leave an empty set of square brackets …

166 abbreviations for location module

---

src/main/python/gui/handconfigspecification_view.py

- Make the default text colour black for handshape slots, so that it's visible against white background.
- Remove green border for field numbers.

Updated slot style to make the default text colour black

---

src/main/python/gui/locationspecification_view.py
src/main/python/gui/modulespecification_widgets.py
src/main/python/gui/nonmanualspecification_view.py
src/main/python/gui/relationspecification_view.py
src/main/python/search/search_classes.py

Also involves refactoring deselectable radio button / buttongroup classes from relation module to a more generally accessible spot. These classes are also referenced by nonmanual module and relation search target.

make location type buttons deselectable

---

src/main/python/search/search_classes.py
src/main/python/search/search_models.py

For "match all" searches involving multiple targets of the same module/target type, the search function was only returning signs if all the specified target values were present in the same module. For example, if the user did a search to match all of "modified G" and "closed modified G" hand configs, the search function would try to find hand configuration modules containing both "modified G" and "closed modified G", which was impossible. This PR updates the "match all" behaviour so that target values can be spread over multiple modules in a sign.

Search multiple module bug

---

src/main/python/gui/nonmanualspecification_view.py
src/main/python/lexicon/module_classes.py

This PR fills in unspecified or underspecified parts of `nonman_specs` when initializing `NonManualModule` so that when importing json, the module is always initialized with a complete structure.

408 allow json imports with fallback non-manual 

---

src/main/python/gui/modulespecification_widgets.py

This PR applies QTabWidget label bolding logic to nested tabs when their parents are selected.
`decide_bold_label()` is a method in `BoldableTabWidget` which checks the children of each tab and determines whether its label should be shown in bold. Currently, it is called when initializing the nonman GUI or when the user selects a tab index. 
Tabs like 'Facial Expression' and 'Mouth' contain an embedded tab, which may need to be bolded. However, since `decide_bold_label()` does not look for a QTabWidget among the content, bolding cannot be aplied to a nested tab recursively.
This PR connects the index change signal to a new method `on_tab_change()`, instead of `decide_bold_label()`. The new method wraps `decide_bold_label()` and applies the bolding logic to the matrix and nested tabs.
As …

Bold highlight subsidiary nonmanual tabs when needed
